In [1]:
# this code conceals irrelevant warning messages
import warnings
warnings.simplefilter('ignore', FutureWarning)

In [4]:
#Creating a numpy array
import numpy as np
arr = np.array([1, 2, 3, 4,5])
print(arr)
print(type(arr))

print(np.__version__)

arr = np.array((1, 2, 3, 4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>
2.5.3
[1 2 3 4 5]
<class 'numpy.ndarray'>

In [9]:
#O-D Array
import numpy as np
arr = np.array(42)
print(arr)

42

In [14]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6
import numpy as np
are = np.array([[1, 2, 3], [4, 5, 6]])
print(are)

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  
print(arr)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

In [16]:
#Number of dimensions
import numpy as np  
a = np.array(42)  
b = np.array([1, 2, 3, 4, 5])  
c = np.array([[1, 2, 3], [4, 5, 6]])  
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  

print(a.ndim)  
print(b.ndim)  
print(c.ndim)  
print(d.ndim)  

#an array with 5 dimensions and verify
arr = np.array([1, 2, 3, 4], ndmin=5)  
print(arr)  
print('number of dimensions :', arr.ndim)

0
1
2
3
[[[[[1 2 3 4]]]]]
number of dimensions : 5

In [24]:
#Numpy array indexing
import numpy as np  
arr = np.array([1, 2, 3, 4])  
print(arr[0]) 
print(arr[1]) 
print(arr[2] + arr[3]) 

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  
print('2nd element on 1st row: ', arr[0, 1]) 
print('5th element on 2nd row: ', arr[1, 4])

#Accessing Elements in 3-D Arrays  
# To access elements from 3-D arrays, use comma-separated integers representing each dimension.  
# Example: Access the third element of the second array of the first array  
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  
print(arr[0, 1, 2]) 

# Negative Indexing  
# Use negative indexing to access elements from the end of an array.  
# Example: Print the last element from the 2nd row  

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  
print('Last element from 2nd dim: ', arr[1, -1])

1
2
7
2nd element on 1st row:  2
5th element on 2nd row:  10
6
Last element from 2nd dim:  10

In [33]:
#slicing
import numpy as np  
arr = np.array([1, 2, 3, 4, 5, 6, 7])  
print(arr[1:5])

arr = np.array([1, 2, 3, 4, 5, 6, 7])  
print(arr[4:]) 
print(arr[:4])  
print(arr[-3:-1])   
print(arr[1:5:2]) 
print(arr[::2]) 

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])  
print(arr[1, 1:4]) 
print(arr[0:2, 2]) #from both rows return index 2
print(arr[0:2, 1:4])  #from both rows, slice index 1 to index 4

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]

In [39]:
#checking the data type of an array
import numpy as np  
arr = np.array([1, 2, 3, 4])  
print(arr.dtype)  

arr = np.array(['apple', 'banana', 'cherry'])  
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')  
print(arr)  
print(arr.dtype)

#creating array with data type 4 bytes integer
arr = np.array([1, 2, 3, 4], dtype='i4')  
print(arr)  
print(arr.dtype) 

#change data type from float to nteger by using i as parameter value
arr = np.array([1.1, 2.1, 3.1])  
newarr = arr.astype('i')  
print(newarr)  
print(newarr.dtype)

#float to integer using int as parameter value
newarr = arr.astype(int)  
print(newarr)  
print(newarr.dtype) 

#changing type from integer to boolean
arr = np.array([1, 0, 3])  
newarr = arr.astype(bool)  
print(newarr)  
print(newarr.dtype)

int64
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
[1 2 3]
int32
[1 2 3]
int64
[ True False  True]
bool

In [42]:
#copy & view
import numpy as np  
arr = np.array([1, 2, 3, 4, 5])  
x = arr.copy()  
arr[0] = 42  

print(arr)  # [42  2  3  4  5]  
print(x)    # [1  2  3  4  5] copy is not affected by changes made

x = arr.view()  
arr[0] = 42  

print(arr)  # [42  2  3  4  5]  
print(x)    # [42  2  3  4  5]  view is affected by changes made

arr = np.array([1, 2, 3, 4, 5])  
x = arr.copy()  
y = arr.view()  

print(x.base)  # None  
print(y.base)  # [1 2 3 4 5]

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[1 2 3 4 5]

In [8]:
#shape of an array
import numpy as np  
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  
print(arr.shape)# 2, 4 as in 2 row and 4 colums

#Create an array with 5 dimensions using ndmin, verify last dimension has value 4
arr = np.array([1, 2, 3, 4], ndmin=5)  
print(arr)  
print('shape of array :', arr.shape) 

#convert 1D to 2D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])  
newarr = arr.reshape(4, 3)  
print(newarr) 

#reshaping from 1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])  
newarr = arr.reshape(2, 3, 2)  
print(newarr)

#check if it returns copy or view
import numpy as np  
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])  
print(arr.reshape(2, 4).base) 

#conver 1d array with 8 elements to 3d  array with 2x2 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])  
newarr = arr.reshape(2, 2, -1)  
print(newarr) 

#Flattening: Convert the array into a 1D array
arr = np.array([[1, 2, 3], [4, 5, 6]])  
newarr = arr.reshape(-1)  
print(newarr) 

#iterate on the element of a 1d array
arr = np.array([1, 2, 3])  
for x in arr:  
    print(x) 

#on elements with 2d
arr = np.array([[1, 2, 3], [4, 5, 6]])  
for x in arr:  
    print(x) 

#accessing each scalar elements: nest the loop
arr = np.array([[1, 2, 3], [4, 5, 6]])  
for x in arr:  
    for y in x:  
        print(y)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]
1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6

In [21]:
#iterating over a 3d array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  
for x in arr:  
    print(x)

#iterating down to scalars
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  
for x in arr:  
    for y in x:  
        for z in y:  
            print(z) 

#iterating using nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  
for x in np.nditer(arr):  
    print(x)

#array with diff data types
arr = np.array([1, 2, 3])  
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):  
    print(x)  

#iterating with different step size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  
for x in np.nditer(arr[:, ::2]):  
    print(x)

# Enumerate elements of a 1-D array
arr = np.array([1, 2, 3])  
for idx, x in np.ndenumerate(arr):  
    print(idx, x)

# Enumerate elements of a 2-D array  
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  
for idx, x in np.ndenumerate(arr):  
    print(idx, x) 

#Join Two 1-D Arrays
arr1 = np.array([1, 2, 3])  
arr2 = np.array([4, 5, 6])  
arr = np.concatenate((arr1, arr2))  
print(arr)

#Join Two 2-D Arrays Along Rows (axis=1)  
arr1 = np.array([[1, 2], [3, 4]])  
arr2 = np.array([[5, 6], [7, 8]])  
arr = np.concatenate((arr1, arr2), axis=1)  
print(arr)


#Stack Two 1-D Arrays Along a New Axis
arr1 = np.array([1, 2, 3])  
arr2 = np.array([4, 5, 6])  
arr = np.stack((arr1, arr2), axis=1)  
print(arr)

# Stacking Along Rows  

# NumPy provides a helper function: `hstack()` to stack along rows (horizontally).  
arr1 = np.array([1, 2, 3])  
arr2 = np.array([4, 5, 6])  
arr = np.hstack((arr1, arr2))  
print(arr) 

# Stacking Along Columns  

# NumPy provides a helper function: `vstack()` to stack along columns (vertically).   
arr1 = np.array([1, 2, 3])  
arr2 = np.array([4, 5, 6])  
arr = np.vstack((arr1, arr2))  
print(arr) 


# Stacking Along Height (Depth)  

# NumPy provides a helper function: `dstack()` to stack along the third axis (height/depth).  
arr1 = np.array([1, 2, 3])  
arr2 = np.array([4, 5, 6])  
arr = np.dstack((arr1, arr2))  
print(arr)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
1
3
5
7
(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]

In [37]:
#Split the Array into 3 Parts
arr = np.array([1, 2, 3, 4, 5, 6])  
newarr = np.array_split(arr, 3)  
print(newarr)

#into 4 parts
arr = np.array([1, 2, 3, 4, 5, 6])  
newarr = np.array_split(arr, 4)  
print(newarr)

#access the split array
arr = np.array([1, 2, 3, 4, 5, 6])  
newarr = np.array_split(arr, 3)  
print(newarr[0])  
print(newarr[1])  
print(newarr[2])  

#Split a 2-D Array into Three 2-D Arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])  
newarr = np.array_split(arr, 3)  
print(newarr) 

## Example: Split a 2-D Array (Each Element Has 3 Elements)    
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])  
newarr = np.array_split(arr, 3)  
print(newarr)

# You can specify which axis to split around using the `axis` argument.  

#### Example: Split a 2-D Array into Three 2-D Arrays Along Columns (`axis=1`)  
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])  
newarr = np.array_split(arr, 3, axis=1)  
print(newarr) 

#using hsplit: does along column
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])  
newarr = np.hsplit(arr, 3)  
print(newarr)

#search: Find the indexes where the value is 4
arr = np.array([1, 2, 3, 4, 5, 4, 4])  
x = np.where(arr == 4)  
print(x) 

#Find the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])  
x = np.where(arr % 2 == 0)  
print(x)

#Find the indexes where the values are odd
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr % 2 == 1)
print(x)

#Find the index where value 7 should be inserted
arr = np.array([6, 7, 8, 9])  
x = np.searchsorted(arr, 7)  
print(x)

#Search from the Right Side
arr = np.array([6, 7, 8, 9])  
x = np.searchsorted(arr, 7, side='right')  
print(x)

#Searching for Multiple Values
arr = np.array([1, 3, 5, 7])  
x = np.searchsorted(arr, [2, 4, 6])  
print(x) 


#Sort a Numeric Array
arr = np.array([3, 2, 0, 1])  
print(np.sort(arr))

#Sort an Array of Strings
arr = np.array(['banana', 'cherry', 'apple'])  
print(np.sort(arr)) 

## Example: Sort a Boolean Array    
arr = np.array([True, False, True])  
print(np.sort(arr))  

# Sorting a 2-D Array  
# If you use the `sort()` method on a 2-D array, each row will be sorted independently.  
arr = np.array([[3, 2, 4], [5, 0, 1]])  
print(np.sort(arr))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5 6]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
(array([3, 5, 6]),)
(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)
1
2
[1 2 3]
[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]

In [51]:
#NumPy - Array Attributes
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)

# this resizes the ndarray 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a)
#reshape function
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)

#ndarray.ndim
# an array of evenly spaced numbers 
a = np.arange(24) 
print (a)

# this is one dimensional array 
a = np.arange(24) 
print(a.ndim)  

# now reshape it 
b = a.reshape(2,4,3) 
print (b) 
# b is having three dimensions

# array of five zeros. Default dtype is float 
x = np.zeros(5) 
print (x)

# array of five ones. Default dtype is float  
x = np.ones(5) 
print (x)

# convert list to ndarray 

x = [1,2,3] 
a = np.asarray(x) 
print (a)

# 2D Numpy Array
a = np.array([[1,2,3], [4,1,5]]) 
print (a)

# Addition
a+3

# Multiplication
a*2

# Subtraction
a-2

# Division
a/3

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3]
[[1 2 3]
 [4 1 5]]

C:\Users\Beloved\AppData\Local\Temp\ipykernel_18904\1237917579.py:7: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  a.shape = (3,2)

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

In [53]:
#indexing &slicing
a = np.arange(10) 
s = slice(2,7,2) 
print(a[s])
a = np.arange(10) 
b = a[2:7:2] 
print (b)
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a ) 

# slice items starting from index
print('Now we will slice the array from the index a[1:]') 
print(a[1:])

#Numpy 2D Array
a = np.array([[1,2,3],[3,4,5]])
print(a)
a = np.array([[1,2,3], [4,1,5]]) 
print (a)
# Addition
a+3
# Multiplication
a*2
# Subtraction
a-2
# Division
a/3

[2 4 6]
[2 4 6]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]
[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [4 1 5]]

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

In [56]:
#Numpy 2D Array
a = np.array([[1,2,3],[3,4,5]])
print(a)
# Base Ball Player's Heights AS a in 2D 
a = np.array([[1,2,3], [4,1,5]]) 
print (a)
# Addition
a+3
# Multiplication
a*2
# Subtraction
a-2
# Division
a/3

#Subsetting 2D NumPy Arrays

a[0]
a[0][0] # Accessing the first element from the first array
a[1][0] # Accessing the first element from the second array
a[0][1:2] # Accessing from index 1 to 2 elements from the first array
a[1][1:2] # Accessing from index 1 to 2 elements from the second array

#2D Arithmetic

# Addition
a+3
# Multiplication
a*2
# Subtraction
a-2
# Division
a/3

[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [4 1 5]]

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

In [1]:
#time for pandas
import pandas as pd

# Load Data from cohort database (schema week06). See "Data Access (SQL).md".
import sys, pathlib
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query

data = run_query("SELECT * FROM week06.who_pop_tb_some")
data

                  Country  Population (1000s)  TB deaths
0                  Angola               21472       6900
1                  Brazil              200362       4400
2                   China             1393337      41000
3       Equatorial Guinea                 757         67
4           Guinea-Bissau                1704       1200
5                   India             1252140     240000
6              Mozambique               25834      18000
7                Portugal               10608        140
8      Russian Federation              142834      17000
9   Sao Tome and Principe                 193         18
10           South Africa               52776      25000
11            Timor-Leste                1133        990

In [5]:
#total, smallest,largest and average number of deaths due to TB
populationColumn = data['Population (1000s)']
tbColumn = data['TB deaths']
#column methods
tbColumn.sum()
tbColumn.min()
tbColumn.max()

#average
tbColumn.sum() / 12
#tbColumn.mean()
#tbColumn.median()

#to calc smallest and largest deaths
data.sort_values('TB deaths')

#just practice
data.sort_values('Population (1000s)')

data.sort_values('Country')

                  Country  Population (1000s)  TB deaths
0                  Angola               21472       6900
1                  Brazil              200362       4400
2                   China             1393337      41000
3       Equatorial Guinea                 757         67
4           Guinea-Bissau                1704       1200
5                   India             1252140     240000
6              Mozambique               25834      18000
7                Portugal               10608        140
8      Russian Federation              142834      17000
9   Sao Tome and Principe                 193         18
10           South Africa               52776      25000
11            Timor-Leste                1133        990

In [6]:
#calculating death rate of each country
deathsColumn = data['TB deaths']
populationColumn = data['Population (1000s)']
rateColumn = deathsColumn * 100 / populationColumn
rateColumn

0     32.134873
1      2.196025
2      2.942576
3      8.850727
4     70.422535
5     19.167186
6     69.675621
7      1.319759
8     11.901928
9      9.326425
10    47.370017
11    87.378641
dtype: float64

In [7]:
data['TB deaths (per 100,000)'] = rateColumn
data

,Country,Population (1000s),TB deaths,"TB deaths (per 100,000)"
0,Angola,21472,6900,32.134873
1,Brazil,200362,4400,2.196025
2,China,1393337,41000,2.942576
3,Equatorial Guinea,757,67,8.850727
4,Guinea-Bissau,1704,1200,70.422535
5,India,1252140,240000,19.167186
6,Mozambique,25834,18000,69.675621
7,Portugal,10608,140,1.319759
8,Russian Federation,142834,17000,11.901928
9,Sao Tome and Principe,193,18,9.326425
10,South Africa,52776,25000,47.370017
11,Timor-Leste,1133,990,87.378641

In [2]:
#Dataframes and CSV files
# Load Data from cohort database (schema week06). See "Data Access (SQL).md".

_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query

df = run_query("SELECT * FROM week06.who_pop_tb_all")
import sys, pathlib

df.columns

#to display dataframes role
#iloc(), head(), tail()
df.iloc[0] # first row, index 0

df.iloc[2] # third row, index 2

NameError: name 'pathlib' is not defined

In [13]:
df.head() # first five rows

df.head(7) # first seven rows

               Country  Population (1000s)  TB deaths
0          Afghanistan               30552   13000.00
1              Albania                3173      20.00
2              Algeria               39208    5100.00
3              Andorra                  79       0.26
4               Angola               21472    6900.00
5  Antigua and Barbuda                  90       1.20
6            Argentina               41446     570.00

In [14]:
df.tail() # last five rows

                                Country  Population (1000s)  TB deaths
189  Venezuela (Bolivarian Republic of)               30405      480.0
190                            Viet Nam               91680    17000.0
191                               Yemen               24407      990.0
192                              Zambia               14539     3600.0
193                            Zimbabwe               14150     5700.0

In [17]:
df['TB deaths']

df['TB deaths'].head()
df['TB deaths'].iloc[2]

df[['Country']].head()

       Country
0  Afghanistan
1      Albania
2      Algeria
3      Andorra
4       Angola

In [18]:
df[['Country', 'Population (1000s)']].head()

       Country  Population (1000s)
0  Afghanistan               30552
1      Albania                3173
2      Algeria               39208
3      Andorra                  79
4       Angola               21472

In [20]:
#applying methods to dataframe column
df['TB deaths'].iloc[2] # third value of deaths column

df['Population (1000s)'].tail() # last five values of population column

189    30405
190    91680
191    24407
192    14539
193    14150
Name: Population (1000s), dtype: int64

In [21]:
df[df['Population (1000s)'] > 80000]

                      Country  Population (1000s)  TB deaths
13                 Bangladesh              156595    80000.0
23                     Brazil              200362     4400.0
36                      China             1393337    41000.0
53                      Egypt               82056      550.0
58                   Ethiopia               94101    30000.0
65                    Germany               82727      300.0
77                      India             1252140   240000.0
78                  Indonesia              249866    64000.0
85                      Japan              127144     2100.0
109                    Mexico              122332     2200.0
124                   Nigeria              173615   160000.0
128                  Pakistan              182143    49000.0
134               Philippines               98394    27000.0
141        Russian Federation              142834    17000.0
185  United States of America              320051      490.0
190                  Viet Nam               91680    17000.0

In [22]:
df[(df['Population (1000s)'] > 80000) & (df['TB deaths'] > 10000)]

                Country  Population (1000s)  TB deaths
13           Bangladesh              156595    80000.0
36                China             1393337    41000.0
58             Ethiopia               94101    30000.0
77                India             1252140   240000.0
78            Indonesia              249866    64000.0
124             Nigeria              173615   160000.0
128            Pakistan              182143    49000.0
134         Philippines               98394    27000.0
141  Russian Federation              142834    17000.0
190            Viet Nam               91680    17000.0

In [23]:
population = df['Population (1000s)']
deaths = df['TB deaths']
df[(population > 80000) & (deaths > 10000)]

                Country  Population (1000s)  TB deaths
13           Bangladesh              156595    80000.0
36                China             1393337    41000.0
58             Ethiopia               94101    30000.0
77                India             1252140   240000.0
78            Indonesia              249866    64000.0
124             Nigeria              173615   160000.0
128            Pakistan              182143    49000.0
134         Philippines               98394    27000.0
141  Russian Federation              142834    17000.0
190            Viet Nam               91680    17000.0